# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livescore', '0002_auto_20170210_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batsman',
            old_name='upload_date',
            new_name='Out_date',
        ),
        migrations.RenameField(
            model_name='batsman',
            old_name='run_date',
            new_name='playing_date',
        ),
    ]
